/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

// Import Routes

import { Route as rootRoute } from './routes/__root'
import { Route as IndexImport } from './routes/index'
import { Route as ContactsIndexImport } from './routes/contacts/index'
import { Route as ContactsCreateImport } from './routes/contacts/create'
import { Route as ContactsContactIdIndexImport } from './routes/contacts/$contactId/index'
import { Route as ContactsContactIdEditImport } from './routes/contacts/$contactId/edit'

// Create/Update Routes

const IndexRoute = IndexImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRoute,
} as any)

const ContactsIndexRoute = ContactsIndexImport.update({
  id: '/contacts/',
  path: '/contacts/',
  getParentRoute: () => rootRoute,
} as any)

const ContactsCreateRoute = ContactsCreateImport.update({
  id: '/contacts/create',
  path: '/contacts/create',
  getParentRoute: () => rootRoute,
} as any)

const ContactsContactIdIndexRoute = ContactsContactIdIndexImport.update({
  id: '/contacts/$contactId/',
  path: '/contacts/$contactId/',
  getParentRoute: () => rootRoute,
} as any)

const ContactsContactIdEditRoute = ContactsContactIdEditImport.update({
  id: '/contacts/$contactId/edit',
  path: '/contacts/$contactId/edit',
  getParentRoute: () => rootRoute,
} as any)

// Populate the FileRoutesByPath interface

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexImport
      parentRoute: typeof rootRoute
    }
    '/contacts/create': {
      id: '/contacts/create'
      path: '/contacts/create'
      fullPath: '/contacts/create'
      preLoaderRoute: typeof ContactsCreateImport
      parentRoute: typeof rootRoute
    }
    '/contacts/': {
      id: '/contacts/'
      path: '/contacts'
      fullPath: '/contacts'
      preLoaderRoute: typeof ContactsIndexImport
      parentRoute: typeof rootRoute
    }
    '/contacts/$contactId/edit': {
      id: '/contacts/$contactId/edit'
      path: '/contacts/$contactId/edit'
      fullPath: '/contacts/$contactId/edit'
      preLoaderRoute: typeof ContactsContactIdEditImport
      parentRoute: typeof rootRoute
    }
    '/contacts/$contactId/': {
      id: '/contacts/$contactId/'
      path: '/contacts/$contactId'
      fullPath: '/contacts/$contactId'
      preLoaderRoute: typeof ContactsContactIdIndexImport
      parentRoute: typeof rootRoute
    }
  }
}

// Create and export the route tree

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/contacts/create': typeof ContactsCreateRoute
  '/contacts': typeof ContactsIndexRoute
  '/contacts/$contactId/edit': typeof ContactsContactIdEditRoute
  '/contacts/$contactId': typeof ContactsContactIdIndexRoute
}

export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/contacts/create': typeof ContactsCreateRoute
  '/contacts': typeof ContactsIndexRoute
  '/contacts/$contactId/edit': typeof ContactsContactIdEditRoute
  '/contacts/$contactId': typeof ContactsContactIdIndexRoute
}

export interface FileRoutesById {
  __root__: typeof rootRoute
  '/': typeof IndexRoute
  '/contacts/create': typeof ContactsCreateRoute
  '/contacts/': typeof ContactsIndexRoute
  '/contacts/$contactId/edit': typeof ContactsContactIdEditRoute
  '/contacts/$contactId/': typeof ContactsContactIdIndexRoute
}

export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/contacts/create'
    | '/contacts'
    | '/contacts/$contactId/edit'
    | '/contacts/$contactId'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/contacts/create'
    | '/contacts'
    | '/contacts/$contactId/edit'
    | '/contacts/$contactId'
  id:
    | '__root__'
    | '/'
    | '/contacts/create'
    | '/contacts/'
    | '/contacts/$contactId/edit'
    | '/contacts/$contactId/'
  fileRoutesById: FileRoutesById
}

export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  ContactsCreateRoute: typeof ContactsCreateRoute
  ContactsIndexRoute: typeof ContactsIndexRoute
  ContactsContactIdEditRoute: typeof ContactsContactIdEditRoute
  ContactsContactIdIndexRoute: typeof ContactsContactIdIndexRoute
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  ContactsCreateRoute: ContactsCreateRoute,
  ContactsIndexRoute: ContactsIndexRoute,
  ContactsContactIdEditRoute: ContactsContactIdEditRoute,
  ContactsContactIdIndexRoute: ContactsContactIdIndexRoute,
}

export const routeTree = rootRoute
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

/* ROUTE_MANIFEST_START
{
  "routes": {
    "__root__": {
      "filePath": "__root.tsx",
      "children": [
        "/",
        "/contacts/create",
        "/contacts/",
        "/contacts/$contactId/edit",
        "/contacts/$contactId/"
      ]
    },
    "/": {
      "filePath": "index.tsx"
    },
    "/contacts/create": {
      "filePath": "contacts/create.tsx"
    },
    "/contacts/": {
      "filePath": "contacts/index.tsx"
    },
    "/contacts/$contactId/edit": {
      "filePath": "contacts/$contactId/edit.tsx"
    },
    "/contacts/$contactId/": {
      "filePath": "contacts/$contactId/index.tsx"
    }
  }
}
ROUTE_MANIFEST_END */
